version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    container_name: cnab_db 
    ports: 
      - "5432:5432"
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CNAB_DB
    volumes: 
      - pgdata:/data/postgres

volumes: 
  pgdata: 
    driver: local