# Generated by Django 3.2.13 on 2022-04-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnabTransactionsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=30)),
                ('nature', models.CharField(max_length=10)),
                ('signal', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Cnab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.CharField(max_length=11)),
                ('card', models.CharField(max_length=12)),
                ('hour', models.TimeField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.store')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cnabtransactionsTypes', to_field='type')),
            ],
        ),
    ]
